### ISSUE TITLE
Issues with --input.blacklist_dir

### ISSUE THREAD

**Issue by TomSmartBishop** [foonathan/standardese#45]
Running standardese with --input.blacklist_file x86intrin.h --input.blacklist_dir compiler ../../inc/ gives me the following error:
[critical] when parsing '<unknown>' (/home/cabox/workspace/inc/compiler/push:11): ill formed preprocessor directive (Boost.Wave)

However according to the help it should ignore anything beyond 'compiler', right?

**Comment by TomSmartBishop** [comment]
Tried to work around it with --input.blacklist_ext . but it still tries to parse /workspace/inc/compiler/push

**Comment by foonathan** [comment]
I cannot reproduce the issue.
Which version are you using on which platform?

**Comment by TomSmartBishop** [comment]
Ubuntu 14.04 (64 bit), libclang-3.8, boost 1.54 (I know for boost this is one version below your recommendation - in case this is the trouble maker it might be worth another check for the version in cmake). I cloned standardese today...

**Comment by foonathan** [comment]
You cloned the master branch I presume?

Hm, it might be an issue with Boost.ProgramOptions not recognizing the options, there are a few bugfixes since then. Could you add a loop [here](https://github.com/foonathan/standardese/blob/master/tool/main.cpp#L179) that just loops over the blacklist_dir vector and prints each element?

**Comment by foonathan** [comment]
Any update on this?
